on:
  push:
     branches:
       - natling

name: renderbook

jobs:
  bookdown:
    name: Render-Book
    concurrency: ci-${{ github.ref }}
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-renv@v2

      - name: Cache bookdown results
        uses: actions/cache@v2
        with:
          path: _bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-

      - name: Render Book
        run: Rscript -e 'rmarkdown::render_site()'

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: current

      - name: install
        run: npm install
      - name: build
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: natling
          target-folder: docs
          folder: docs
